stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_cleaning:
    cmd: python src/data_cleaning.py
    deps:
    - data/raw
    - src/data_cleaning.py
    outs:
    - data/cleaning
  model_building:
    cmd: python src/model_build.py
    deps:
    - data/feature_eng
    - src/model_build.py
    outs:
    - data/model_evaluation
