stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_cleaning:
    cmd: python src/data_cleaning.py
    deps:
    - data/raw
    - src/data_cleaning.py
    outs:
    - data/cleaning
  model_building:
    cmd: python src/model_build.py
    deps:
    - data/feature_eng
    - src/model_build.py
    outs:
    - data/model_evaluation
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- dvclive/plots/sklearn/roc.json:
    template: simple
    x: fpr
    y: tpr
    title: Receiver operating characteristic (ROC)
    x_label: False Positive Rate
    y_label: True Positive Rate
- dvclive/plots/sklearn/calibration.json:
    template: simple
    x: prob_pred
    y: prob_true
    title: Calibration Curve
    x_label: Mean Predicted Probability
    y_label: Fraction of Positives
